#!/bin/bash

echo "🔧 Testing Gen Commands Bug Fix..."
echo ""
echo "✅ Changes made:"
echo "  - Removed gen.select_model() calls (causes model selection screen)"
echo "  - Using gen.exec() with explicit model parameter"
echo "  - Added vim.tbl_extend() to merge options properly"
echo ""
echo "📋 Commands to test manually:"
echo "  1. :GenQwen    - Should prompt 'Query:' directly (no model menu)"
echo "  2. :GenDeepSeek - Should prompt 'Query:' directly (no model menu)"
echo "  3. :GenPhi     - Should prompt 'Query:' directly (no model menu)"
echo "  4. :GenChat    - Should show model menu, then prompt 'Query:'"
echo ""
echo "  Keybindings:"
echo "  - <leader>gq   - GenQwen"
echo "  - <leader>gd   - GenDeepSeek"
echo "  - <leader>gp   - GenPhi"
echo "  - <leader>gc   - GenChat (menu first)"
echo ""
echo "🧪 Quick test:"
echo "  nvim +'set shortmess+=I' +GenQwen"
echo ""
echo "Expected behavior:"
echo "  1. Notification: 'Gen → Qwen 2.5 Coder 14B...'"
echo "  2. Context summary notification"
echo "  3. Input prompt: 'Query:' (NOT a model selection menu)"
echo "  4. After response, continuation prompt appears"
echo ""
echo "If you still see model selection:"
echo "  1. Restart Neovim completely (:qa! and reopen)"
echo "  2. Run :Lazy sync to reload plugins"
echo "  3. Check for Lazy.nvim cache issues"
