#!/bin/bash

echo "🧪 Coplito RAG System - Complete Test Suite"
echo "==========================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test counter
TESTS_PASSED=0
TESTS_FAILED=0

# Create test file
cat > /tmp/test_code.py << 'EOF'
def calculate_sum(x, y):
    return x + z  # BUG: z is undefined

def divide(a, b):
    return a / b  # BUG: no zero check

class UserManager:
    def __init__(self):
        self.users = []
    
    def add_user(self, name):
        self.users.append(name)
        return True
EOF

echo "📁 Created test file: /tmp/test_code.py"
echo ""

# Test 1: Simple chat
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 1: Chat Command (Direct Model Access)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Press: <leader>gq  (or :GenQwen)"
echo "3. Type query: 'what does this file do?'"
echo "4. Press Enter"
echo ""
echo "Expected result:"
echo "  ✅ Shows notification: 'Gen → Qwen 2.5 Coder 14B...'"
echo "  ✅ Shows context summary with file info"
echo "  ✅ Opens vertical split with AI response"
echo "  ✅ Response mentions Python functions from file"
echo "  ✅ After response, shows 'Continue?' prompt"
echo ""
read -p "Press Enter to continue to next test..."

# Test 2: Fix code with visual selection
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 2: Fix Code (Visual Selection + LSP)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Wait for LSP to load (1-2 seconds)"
echo "3. Move cursor to line 2 (return x + z)"
echo "4. Press V to enter visual line mode"
echo "5. Press Ctrl+Shift+i"
echo "6. Select: '🔧 Fix Code'"
echo "7. Select: 'DeepSeek Coder V2 16B'"
echo "8. Press Enter (or type 'fix this')"
echo ""
echo "Expected result:"
echo "  ✅ Shows context summary"
echo "  ✅ RAG includes LSP error: 'undefined name \"z\"'"
echo "  ✅ Replaces selection with fixed code: 'return x + y'"
echo ""
read -p "Press Enter to continue to next test..."

# Test 3: Review code
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 3: Review Code (Comprehensive Analysis)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Select divide function (lines 4-5) in visual mode"
echo "3. Press Ctrl+Shift+i"
echo "4. Select: '🔍 Review Code'"
echo "5. Select: 'DeepSeek Coder V2 16B'"
echo "6. Press Enter"
echo ""
echo "Expected result:"
echo "  ✅ Shows context summary"
echo "  ✅ Review mentions: 'No zero check for division'"
echo "  ✅ Suggests: 'Add ZeroDivisionError handling'"
echo "  ✅ Opens in vertical split (doesn't replace)"
echo ""
read -p "Press Enter to continue to next test..."

# Test 4: Explain code
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 4: Explain Code (with Context)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Select UserManager class (lines 7-13) in visual mode"
echo "3. Press Ctrl+Shift+i"
echo "4. Select: '📝 Explain Code'"
echo "5. Select: 'Qwen 2.5 Coder 14B'"
echo "6. Press Enter"
echo ""
echo "Expected result:"
echo "  ✅ Shows context summary"
echo "  ✅ Explanation describes class purpose"
echo "  ✅ Mentions __init__ and add_user methods"
echo "  ✅ Explains self.users list"
echo ""
read -p "Press Enter to continue to next test..."

# Test 5: Context inspection
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 5: Context Inspection Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Run: :CopiloContext"
echo "3. Run: :CopiloErrors"
echo "4. Run: :CopiloSymbols"
echo ""
echo "Expected result:"
echo "  :CopiloContext"
echo "    ✅ Shows: 'Errors: 2' (z undefined, no zero check)"
echo "    ✅ Shows: 'Symbols: 3-4' (functions + class)"
echo "    ✅ Shows: 'File: /tmp/test_code.py'"
echo ""
echo "  :CopiloErrors"
echo "    ✅ Shows: 'Found 2 error(s) in buffer'"
echo ""
echo "  :CopiloSymbols"
echo "    ✅ Shows: 'Found 3-4 symbols in buffer'"
echo ""
read -p "Press Enter to continue to next test..."

# Test 6: Preview prompt
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 6: Preview RAG Prompt Structure"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Run: :CopiloPreview"
echo "3. Type query: 'what are the bugs?'"
echo "4. Press Enter"
echo ""
echo "Expected result:"
echo "  ✅ Opens split showing full structured prompt"
echo "  ✅ Contains: [ERROR CONTEXT] section with LSP errors"
echo "  ✅ Contains: [CODE CONTEXT] section with file content"
echo "  ✅ Contains: [USER QUERY] section with your question"
echo "  ✅ Contains: [RESPONSE RULES] section"
echo ""
read -p "Press Enter to continue to next test..."

# Test 7: Enhance code
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 7: Enhance Code (Refactoring)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Select calculate_sum function (lines 1-2) in visual mode"
echo "3. Press Ctrl+Shift+i"
echo "4. Select: '✨ Enhance Code'"
echo "5. Select: 'Qwen 2.5 Coder 14B'"
echo "6. Press Enter"
echo ""
echo "Expected result:"
echo "  ✅ Shows context summary"
echo "  ✅ Replaces with enhanced version including:"
echo "      - Type hints (def calculate_sum(x: int, y: int) -> int)"
echo "      - Docstring"
echo "      - Fixed bug (z → y)"
echo "      - Better error handling"
echo ""
read -p "Press Enter to continue to next test..."

# Test 8: Continuation
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 8: Multi-turn Conversation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "How to test:"
echo "1. Open test file: nvim /tmp/test_code.py"
echo "2. Press: <leader>gq"
echo "3. Type: 'what is the calculate_sum function?'"
echo "4. Wait for response"
echo "5. In continuation prompt, type: 'what about divide?'"
echo "6. Wait for response"
echo "7. In continuation prompt, type: 'are there any bugs?'"
echo ""
echo "Expected result:"
echo "  ✅ First response explains calculate_sum"
echo "  ✅ Second response explains divide"
echo "  ✅ Third response mentions both bugs"
echo "  ✅ Can continue indefinitely"
echo "  ✅ Press Esc to exit conversation"
echo ""
read -p "Press Enter to continue to next test..."

# Test 9: All keybindings
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TEST 9: All Keybindings"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Keybindings to test:"
echo ""
echo "Direct model access (Normal mode):"
echo "  <leader>gq  → Qwen"
echo "  <leader>gd  → DeepSeek"
echo "  <leader>gp  → Phi"
echo ""
echo "Menu-based (Normal mode):"
echo "  <leader>gc  → Model menu → Chat"
echo "  Ctrl+Shift+i → Prompt menu"
echo ""
echo "Code operations (Visual mode):"
echo "  <leader>ge  → Explain"
echo "  <leader>gf  → Fix"
echo "  <leader>gr  → Review"
echo ""
echo "Context inspection (Normal mode):"
echo "  <leader>ci  → Show context"
echo "  <leader>cp  → Preview prompt"
echo "  <leader>ce  → Check errors"
echo "  <leader>cs  → Show symbols"
echo ""
echo "All should work without errors!"
echo ""
read -p "Press Enter to see quick test commands..."

# Quick test commands
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "QUICK TEST COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Copy and paste these into your terminal:"
echo ""
echo "# Open test file"
echo "nvim /tmp/test_code.py"
echo ""
echo "# Then inside Neovim, try these:"
echo ":CopiloContext     # Check what RAG sees"
echo ":CopiloErrors      # Check LSP errors"
echo ":GenQwen           # Start chat with Qwen"
echo ""
echo "# Or use keybindings:"
echo "# <leader>gq → Type: 'summarize this file'"
echo "# Vj → <leader>gf → Fix first function"
echo ""

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Test file ready: /tmp/test_code.py"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Quick start: nvim /tmp/test_code.py"
echo ""
